name: Sync Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Backup workflow
        run: cp .github/workflows/sync_upstream.yml /tmp/

      - name: Add upstream
        run: |
          git remote add upstream https://github.com/jwyGithub/sub-convert.git
          git fetch upstream --prune

      - name: Check release branch existence
        id: check_release
        run: |
          if git ls-remote --exit-code upstream release; then
            echo "release_exists=true" >> $GITHUB_OUTPUT
          else
            echo "release_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Sync main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git reset --hard upstream/main
          
          mkdir -p .github/workflows
          cp /tmp/sync_upstream.yml .github/workflows/
          
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add .github/workflows/sync_upstream.yml
          git commit -m "chore: keep sync workflow" || echo "No changes"
          git push origin main --force

      - name: Sync release branch
        if: ${{ steps.check_release.outputs.release_exists == 'true' }}
        run: |
          git checkout -b release upstream/release
          git push origin release --force
